version : 2.1

executors:
  default_executor:
    docker:
      - image: cimg/base:current
    resource_class: small

jobs:
  one:
    executor: default_executor
    steps:
      - run: echo "hello john"
  two:
    executor: default_executor
    steps:
      - run: echo $something
  three:
    executor: default_executor
    steps:
      - run: echo $something


workflows:
  workflow:
    jobs:
      - one
      - two:
          requires:
            - one
          context:
            - SENSITIVE_CONTEXT
      - three:
          context:
            - SENSITIVE_CONTEXT
          filters:
            branches:
              only: /^main$/
          requires:
            - two
